/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jinwang_yongbao_device_Device */

#ifndef _Included_com_jinwang_yongbao_device_Device
#define _Included_com_jinwang_yongbao_device_Device
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jinwang_yongbao_device_Device
 * Method:    uartInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jinwang_yongbao_device_Device_uartInit
  (JNIEnv *, jobject);

/*
 * Class:     com_jinwang_yongbao_device_Device
 * Method:    uartDestroy
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jinwang_yongbao_device_Device_uartDestroy
  (JNIEnv *, jobject);

/*
 * Class:     com_jinwang_yongbao_device_Device
 * Method:    openGrid
 * Signature: (II[I)I
 */
JNIEXPORT jint JNICALL Java_com_jinwang_yongbao_device_Device_openGrid
  (JNIEnv *, jobject, jint, jint, jintArray);

/*
 * Class:     com_jinwang_yongbao_device_Device
 * Method:    getBoardAddress
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_jinwang_yongbao_device_Device_getBoardAddress
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_jinwang_yongbao_device_Device
 * Method:    getDoorState
 * Signature: (II[I)I
 */
JNIEXPORT jint JNICALL Java_com_jinwang_yongbao_device_Device_getDoorState
  (JNIEnv *, jobject, jint, jint, jintArray);

/*
 * Class:     com_jinwang_yongbao_device_Device
 * Method:    getProtocalID
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_jinwang_yongbao_device_Device_getProtocalID
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
